---
# List of packages to install.
kolla_ansible_package_dependencies:
  - gcc
  - libffi-devel
  - openssl-devel
  - patch
  - "python{% if kolla_ansible_venv_python_major_version | int == 3 %}3{% endif %}-devel"
  - "python{% if kolla_ansible_venv_python_major_version | int == 3 %}3{% endif %}-pip"
  - "{% if kolla_ansible_venv_python_major_version | int == 2 %}python-virtualenv{% endif %}"
  - "{% if kolla_ansible_venv_python_major_version | int == 2 %}PyYAML{% endif %}"
