---
- hosts: primary
  vars:
    logs_dir: "/tmp/logs"
    kayobe_src_dir: "{{ ansible_env.PWD ~ '/' ~ zuul.projects['opendev.org/x/kayobe'].src_dir }}"
    kayobe_config_src_dir: "{{ ansible_env.PWD ~ '/' ~ zuul.projects['opendev.org/x/kayobe-config-dev'].src_dir }}"
    previous_kayobe_src_dir: "{{ ansible_env.PWD ~ '/previous/kayobe' }}"
    previous_kayobe_config_src_dir: "{{ ansible_env.PWD ~ '/previous/kayobe-config' }}"
  roles:
    - role: kayobe-diagnostics
      kayobe_diagnostics_phase: "pre"
      kayobe_diagnostics_log_dir: "{{ logs_dir }}"

    - role: kayobe-ci-prep
  tasks:
    # NOTE(mgoddard): Copying upper constraints to somewhere accessible by both
    # the zuul and stack users.
    - name: Ensure upper-contraints.txt exists
      copy:
        src: "{{ zuul.projects['opendev.org/openstack/requirements'].src_dir ~ '/upper-constraints.txt' }}"
        dest: "/tmp"
        mode: 0644
        remote_src: true

    - name: Ensure previous kayobe directory exists
      file:
        path: "{{ previous_kayobe_src_dir }}"
        state: directory

    - name: Ensure previous kayobe repository is cloned
      git:
        repo: https://opendev.org/x/kayobe
        dest: "{{ previous_kayobe_src_dir }}"
        version: "stable/{{ previous_release | lower }}"

    - name: Ensure previous kayobe-config directory exists
      file:
        path: "{{ previous_kayobe_config_src_dir }}"
        state: directory

    - name: Ensure kayobe-config repository is cloned
      git:
        repo: https://opendev.org/x/kayobe-config-dev
        dest: "{{ previous_kayobe_config_src_dir }}"
        version: "stable/{{ previous_release | lower }}"

    # NOTE(mgoddard): Use the name zz-overrides.yml to ensure this takes
    # precedence over the standard config files.
    - name: Ensure kayobe-config override config file exists
      template:
        src: overrides.yml.j2
        dest: "{{ previous_kayobe_config_src_dir }}/etc/kayobe/zz-overrides.yml"
      vars:
        is_previous_release: true

    # NOTE(mgoddard): The kayobe dev config by default expects a bridge -
    # breth1 - to exist with an IP address of 192.168.33.3.
    - name: Ensure all-in-one network bridge interface exists
      command: "{{ item }}"
      become: true
      with_items:
        - "ip l add breth1 type bridge"
        - "ip l set breth1 up"
        - "ip a add 192.168.33.3/24 dev breth1"
