---
- name: Create local .pip directory for {{ user }}
  file:
    path: "~{{ user }}/.pip"
    state: directory
  become: True
  become_user: "{{ user }}"

- name: Create pip.conf for {{ user }}
  copy:
    content: |
      [global]
      {% if pip_index_url | length > 0 -%}
      index-url = {{ pip_index_url }}
      {% endif -%}
      {% if pip_trusted_hosts | length > 0 -%}
      trusted-host =
        {% for host in pip_trusted_hosts | unique -%}
        {{ host }}
        {% endfor -%}
      {% endif -%}
    dest: "~{{ user}}/.pip/pip.conf"
  become: True
  become_user: "{{ user }}"

- name: Create .pydistutils.cfg for {{ user }}
  copy:
    content: |
      [easy_install]
      index-url = {{ pip_index_url }}
    dest: "~{{ user}}/.pydistutils.cfg"
  when: pip_index_url | length > 0
  become: True
  become_user: "{{ user }}"
