---
# Type of Dell switch. One of dellos6, dellos9, or dellos10.
dell_switch_type:

# Authentication provider information.
dell_switch_provider:

# List of configuration lines to apply to the switch.
dell_switch_config: []

# Interface configuration. Dict mapping switch interface names to configuration
# dicts. Each dict contains a 'description' item and a 'config' item which
# should contain a list of per-interface configuration.
dell_switch_interface_config: {}

# Whether to save the configuration.
dell_switch_save: false
