---
- name: Ensure DellOS6 switches are configured
  local_action:
    module: dellos6_config
    provider: "{{ dell_switch_provider }}"
    src: "{{ lookup('template', 'dellos6-config.j2') }}"
  when: dell_switch_type == 'dellos6'

- name: Ensure DellOS9 switches are configured
  local_action:
    module: dellos9_config
    provider: "{{ dell_switch_provider }}"
    src: "{{ lookup('template', 'dellos9-config.j2') }}"
  when: dell_switch_type == 'dellos9'

- name: Ensure DellOS10 switches are configured
  local_action:
    module: dellos10_config
    provider: "{{ dell_switch_provider }}"
    src: "{{ lookup('template', 'dellos10-config.j2') }}"
  when: dell_switch_type == 'dellos10'
