---
# Deploy/pull/reconfigure/upgrade the Prometheus Node Exporter.
#
# Follows kolla-ansible service deployment patterns.
#
# Variables:
# action: One of deploy, destroy, pull, reconfigure, upgrade

- name: Ensure Node Exporter is deployed
  hosts: overcloud:&docker
  tags:
    - node-exporter
  roles:
    - role: node-exporter
      nodeexporter_action: "{{ kayobe_action }}"
