---
- name: Ensure NTP is installed and configured
  hosts: seed-hypervisor:seed:overcloud
  tags:
    - ntp
  roles:
    - role: stackhpc.timezone
      become: True
    - role: stackhpc.ntp
      become: True
