---
# Path to a directory in which to create a virtualenv.
projects_venv:

# Authentication type as used by os_* modules' 'auth_type' argument.
projects_auth_type:

# Authentication options for admin as used by os_* modules' 'auth' argument.
projects_admin_auth: {}

# Environment variables for use with os_* modules.
projects_environment:
  OS_IDENTITY_API_VERSION: 3

# List of projects to create.
# Each item should be a dict containing the following items:
# 'name': The name of the project.
# 'description': A description of the project.
# 'project_domain': The domain in which to register the project.
# 'user_domain': The domain in which to register users.
# 'users': List of users to register. Each user should be a dict containing
#          the following items:
#          'name': The name of the user.
#          'password': The user's password.
#          'roles': A list of roles to assign to the user.
#          'openrc_file': Path to an environment file to create.
# 'keypairs': List of SSH key pairs to register with Nova. Each key pair
#             should be a dict containing the following items:
#             'name': The name of the keypair.
#             'public_key': The SSH public key contents. Optional.
#             'public_key_file': Path to the SSH public key on the control
#                                host.
# 'quotas': Dict mapping quota names to their values.
projects: []
