---
# Path to directory for kolla source code checkout.
kolla_source_path:

# Type of Kolla control installation. One of 'binary' or 'source'.
kolla_ctl_install_type:

# URL of Kolla source code repository if type is 'source'.
kolla_source_url:

# Version (branch, tag, etc.) of Kolla source code repository if type is
# 'source'.
kolla_source_version:

# Virtualenv directory where Kolla will be installed.
kolla_venv: "{{ ansible_facts.env['PWD'] }}/kolla-venv"

# Upper constraints file which is passed to pip when installing packages
# into the kolla venv.
kolla_upper_constraints_file:

# Whether to install the epel-release package.
kolla_install_epel: false

# Directory where Kolla config files will be installed.
kolla_build_config_path:

# Kolla OpenStack release version. This should be a Docker image tag.
kolla_openstack_release:
