---
# Path to a directory in which to create a virtualenv.
ironic_inspector_venv:

# Upper constraints file for installation of python-ironicclient.
ironic_inspector_upper_constraints_file:

# Authentication type.
ironic_inspector_auth_type:

# Authentication information.
ironic_inspector_auth: {}

# CA certificate path.
ironic_inspector_cacert:

# Name of cloud in clouds.yaml.
ironic_inspector_cloud:

# Interface (public, internal, admin).
ironic_inspector_interface:

# List of rules which should exist. See the Inspector rules API for details of
# parameters available for rules.
ironic_inspector_rules: []
